# Generated by Django 3.2.9 on 2021-11-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='is_leo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
