# Generated by Django 3.2.9 on 2021-11-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0003_user_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='story',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_leo',
            field=models.BooleanField(default=True),
        ),
    ]
