# Generated by Django 3.2.9 on 2021-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0004_auto_20211128_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
